### ISSUE TITLE
Feature: Datasets

### ISSUE THREAD

**Issue by rangerscience** [astorfi/Deep-Learning-World#1]
It would be nice to have links to data sets of varying sizes / complexity, so that I can find one that matches my current understanding and computational capacity.

Example: If I am just beginning, I would want a data set that is complex enough to require deep learning (aka, linear regression is not enough) but small and simple enough that I can run a sufficient neural net on my MacBook Pro / Amazon EC2 instance.

**Comment by astorfi** [comment]
Thanks for your attention.
Is under development.
